name: K8s Skipper
on:
  workflow_call:
    inputs:
      base-ref:
        description: "Base of pull-request or merge-group"
        type: string
        required: true
      event-name:
        description: "The kind of event"
        type: string
        required: true
    outputs:
      skip-k8s:
        description: "Whether k8s-ci should run"
        value: ${{ jobs.check.outputs.skip-k8s }}

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      skip-k8s: ${{ steps.skip.outputs.skip-k8s }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: docs
        if: ${{ inputs.event-name == 'pull_request' || inputs.event-name == 'merge_group' }}
        run: |
          BASE_REF="${{ inputs.base-ref }}"
          BASE_SHA=$(git rev-parse origin/${BASE_REF#refs/heads/})
          CHANGED_FILES=$(git diff --name-only $BASE_SHA HEAD)
          NON_MD_FILES=$(echo "$CHANGED_FILES" | grep -vE '^([^/]+\.md)$' || true)

          if [ -z "$NON_MD_FILES" ]; then
            echo "docs-only=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          if [ "${{ inputs.event-name }}" = "pull-request" ]; then
            echo "docs-only=false" >> $GITHUB_OUTPUT
            exit 0
          fi

      - id: merge-q
        if: ${{ inputs.event-name == 'merge_group' }}
        run: |
          BASE_REF="${{ inputs.base-ref }}"

          if git diff --quiet HEAD~1 origin/${BASE_REF#refs/heads/}; then
            echo "skip-check=true" >> $GITHUB_OUTPUT
            echo "Y"
          else
            echo "skip-check=false" >> $GITHUB_OUTPUT
            echo "N"
          fi
          git show HEAD~1
          git show origin/${BASE_REF#refs/heads/}

          PAGER= git diff HEAD~1 origin/${BASE_REF#refs/heads/}
          exit 1

      - id: skip
        run: |
          # PR's just follow the docs changes
          if [ "${{ inputs.event-name }}" = "pull_request" ]; then
            echo "skip-k8s=${{ steps.docs.outputs.docs-only }}" >> $GITHUB_OUTPUT
            exit 0
          fi
          if [ "${{ inputs.event-name }}" = "merge_group" ]; then
            # Otherwise, let's skip only if the tests already passed and we're up to date with base
            echo "skip-k8s=${{ steps.merge-q.outputs.skip-check }}" >> $GITHUB_OUTPUT
            exit 0
          fi
          # else (ie push) we run the tests
          echo "skip-k8s=false" >> $GITHUB_OUTPUT
      - name: skip-k8s?
        run: |
          echo "skip-k8s=${{ steps.skip.outputs.skip-k8s }}"
